In [2]:
import numpy as np


0-D Tensors
Zero dimension tensors hold one point. When operations are performed on the tensor only a single value is changed. 

In [12]:
zeroD = np.array(1)
print(zeroD,"\n num dimensions:",zeroD.ndim)

1 
 num dimensions: 0


1-D Tensor

In [13]:
oneD = np.array([1,2,3])
print(oneD,"\n num dimensions:",oneD.ndim)

[1 2 3] 
 num dimensions: 1


2-D Tensor

In [14]:
twoD = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(twoD,"\n num dimensions:",twoD.ndim)

[[1 2 3]
 [4 5 6]
 [6 7 8]] 
 num dimensions: 2


3-D Tensor

In [16]:
threeD = np.array([[[0,1,2],
                    [3,4,5],
                    [6,7,8]],
                   [[9,10,11],
                    [12,13,14],
                    [15,16,17]]])
print(threeD,"\n num dimensions:",threeD.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] 
 num dimensions: 3
